apiVersion: apps/v1
kind: Deployment
metadata:
  name: tariffcalculator-api-deployment
  namespace: appspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tariffcalculator-api
  template:
    metadata:
      labels:
        app: tariffcalculator-api
    spec:
      containers:
        - name: tariffcalculator-api
          image: 895577162938.dkr.ecr.us-east-1.amazonaws.com/tariffcalculator.api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # Example environment variables â€“ adjust/remove as per your app
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            # - name: ConnectionStrings__DefaultConnection
            #   value: "Server=...;Database=...;User Id=...;Password=..."
---
apiVersion: v1
kind: Service
metadata:
  name: tariffcalculator-api-service
  namespace: appspace
spec:
  type: LoadBalancer
  selector:
    app: tariffcalculator-api
  ports:
    - name: http
      port: 80       # external port
      targetPort: 80 # container port
      protocol: TCP
